{% set version = "0.1.3" %}

package:
  name: sigtool-split
  version: {{ version }}

source:
  url: https://github.com/thefloweringash/sigtool/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 462e7daf144740910dacadab1f1cfde154b405480cf7ec45b5d648f9d293851d
  patches:
    - 0001-find-codesign_allocate-next-to-it.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - openssl

outputs:
  - name: libsigtool
    files:
      - lib/libsigtool*
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make
      host:
        - openssl
    test:
      commands:
        - test -f ${PREFIX}/lib/libsigtool${SHLIB_EXT}

  - name: sigtool-codesign
    files:
      - bin/sigtool-codesign
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make
      host:
        - openssl
      run:
        - {{ pin_subpackage("libsigtool", exact=True) }}
    test:
      commands:
        - sigtool-codesign -h

  - name: sigtool
    files:
      - bin/sigtool
      - bin/codesign
      - include/sigtool
    requirements:
      build:
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - cmake
        - make
      host:
        - openssl
      run:
        - {{ pin_subpackage("libsigtool", exact=True) }}
        - {{ pin_subpackage("sigtool-codesign", exact=True) }}
    test:
      commands:
        - sigtool-codesign -h

about:
  home: https://github.com/thefloweringash/sigtool
  license: MIT
  license_file: LICENSE
  summary: A minimal multicall binary providing helpers for working with embedded signatures in Mach-O files.

extra:
  feedstock-name: sigtool
  recipe-maintainers:
    - isuruf
