{% set version = "0.1.1" %}

package:
  name: sigtool
  version: {{ version }}

source:
  url: https://github.com/thefloweringash/sigtool/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 74daccc37b301f8f0334e651377f2e87c5a1c6e7875c6c18a361d409c4748cc1

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - openssl

test:
  commands:
    - codesign -h

about:
  home: https://github.com/thefloweringash/sigtool
  license: MIT
  license_file: LICENSE
  summary: A minimal multicall binary providing helpers for working with embedded signatures in Mach-O files.

extra:
  recipe-maintainers:
    - isuruf
